import QtQuick
import QtQuick.Controls
import QtQuick.Layouts

Page {
    background: Rectangle {
        color: "#f5f5f5"
    }

    ColumnLayout {
        anchors.fill: parent
        anchors.margins: 20
        spacing: 20

        Label {
            text: "Privacy Policy"
            font.pixelSize: 32
            font.bold: true
            color: "#2196F3"
            Layout.alignment: Qt.AlignHCenter
        }

        // Scrollable area for the long privacy policy content
        ScrollView {
            Layout.fillWidth: true
            Layout.fillHeight: true

            // Privacy Policy Text Area
            Column {
                width: parent.width
                spacing: 20

                // Section 1 - Introduction and Definitions
                Text {
                    text: "Updated at 2022-09-30"
                    font.pixelSize: 16
                    font.bold: true
                    color: "#333333"
                }

                Text {
                    text: "Mazaryn ('we', 'our', or 'us') is committed to protecting your privacy. This Privacy Policy explains how your personal information is collected, used, and disclosed by Mazaryn."
                    font.pixelSize: 16
                    color: "#333333"
                    wrapMode: Text.WordWrap
                }

                Text {
                    text: "This Privacy Policy covers our website, https://mazaryn.io, and subdomains. By using our Service, you agree to our data practices outlined here and in our Terms of Service."
                    font.pixelSize: 16
                    color: "#333333"
                    wrapMode: Text.WordWrap
                }


                // Section 2 - Definitions and Key Terms
                Text {
                    text: "Definitions and Key Terms"
                    font.pixelSize: 18
                    font.bold: true
                    color: "#333333"
                }

                Text {
                    text: "For this Privacy Policy: "
                    font.pixelSize: 16
                    color: "#333333"
                    wrapMode: Text.WordWrap
                }

                // Definition List
                Text {
                    text: "Cookie: Small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information."
                    font.pixelSize: 16
                    color: "#333333"
                    wrapMode: Text.WordWrap
                }

                Text {
                    text: "Company: When this policy mentions 'Company', 'we', 'us', or 'our,' it refers to Mazaryn, 82/9/11 Truong Cong Dinh Street Ward 3, Vung Tau city, Viet Nam that is responsible for your information under this Privacy Policy."
                    font.pixelSize: 16
                    color: "#333333"
                    wrapMode: Text.WordWrap
                }

                Text {
                    text: "Country: Where Mazaryn or the owners/founders of Mazaryn are based, in this case is Iran."
                    font.pixelSize: 16
                    color: "#333333"
                    wrapMode: Text.WordWrap
                }

                Text {
                    text: "Customer: Refers to the company, organization, or person that signs up to use the Mazaryn Service to manage the relationships with your consumers or service users."
                    font.pixelSize: 16
                    color: "#333333"
                    wrapMode: Text.WordWrap
                }

                Text {
                    text: "Device: Any internet connected device such as a phone, tablet, computer or any other device that can be used to visit Mazaryn and use the services."
                    font.pixelSize: 16
                    color: "#333333"
                    wrapMode: Text.WordWrap
                }

                Text {
                    text: "IP address: A unique number assigned to each device connected to the Internet, often used to identify its geographic location."
                    font.pixelSize: 16
                    color: "#333333"
                    wrapMode: Text.WordWrap
                }


                Text {
                    text: "Personnel: Refers to those individuals who are employed by Mazaryn or are under contract to perform a service on behalf of one of the parties."
                    font.pixelSize: 16
                    color: "#333333"
                    wrapMode: Text.WordWrap
                }

                Text {
                    text: "Personal Data: Any information that directly, indirectly, or in connection with other information - including a personal identification number - allows for the identification or identifiability of a natural person."
                    font.pixelSize: 16
                    color: "#333333"
                    wrapMode: Text.WordWrap
                }

                Text {
                    text: "Service: Refers to the service provided by Mazaryn as described in the relative terms (if available) and on this platform."
                    font.pixelSize: 16
                    color: "#333333"
                    wrapMode: Text.WordWrap
                }

                Text {
                    text: "Third-party service: Refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you."
                    font.pixelSize: 16
                    color: "#333333"
                    wrapMode: Text.WordWrap
                }

                Text {
                    text: "Website: Mazaryn's site, which can be accessed via this URL: https://mazaryn.io"
                    font.pixelSize: 16
                    color: "#333333"
                    wrapMode: Text.WordWrap
                }

                Text {
                    text: "You: A person or entity that is registered with Mazaryn to use the Services."
                    font.pixelSize: 16
                    color: "#333333"
                    wrapMode: Text.WordWrap
                }

                Text {
                                    text: "What Information Do We Collect?"
                                    font.pixelSize: 18
                                    font.bold: true
                                    color: "#333333"
                                }

                                Text {
                                    text: "We collect information from you when you visit our service, register, place an order, subscribe to our newsletter, respond to a survey or fill out a form."
                                    font.pixelSize: 16
                                    color: "#333333"
                                    wrapMode: Text.WordWrap
                                }

                                Text {
                                    text: "The types of information we collect include:"
                                    font.pixelSize: 16
                                    font.bold: true
                                    color: "#333333"
                                    wrapMode: Text.WordWrap
                                }

                                Text {
                                    text: "• Name / Username"
                                    font.pixelSize: 16
                                    color: "#333333"
                                    wrapMode: Text.WordWrap
                                }

                                Text {
                                    text: "• Phone Numbers"
                                    font.pixelSize: 16
                                    color: "#333333"
                                    wrapMode: Text.WordWrap
                                }

                                Text {
                                    text: "• Email Addresses"
                                    font.pixelSize: 16
                                    color: "#333333"
                                    wrapMode: Text.WordWrap
                                }

                                Text {
                                    text: "We also collect information from mobile devices for a better user experience, although these features are completely optional."
                                    font.pixelSize: 16
                                    color: "#333333"
                                    wrapMode: Text.WordWrap
                                }

                                // Section 3 - How We Use The Information
                                Text {
                                    text: "How Do We Use The Information We Collect?"
                                    font.pixelSize: 18
                                    font.bold: true
                                    color: "#333333"
                                }

                                Text {
                                    text: "Any of the information we collect from you may be used in one of the following ways:"
                                    font.pixelSize: 16
                                    color: "#333333"
                                    wrapMode: Text.WordWrap
                                }

                                Text {
                                    text: "• To personalize your experience (your information helps us to better respond to your individual needs)"
                                    font.pixelSize: 16
                                    color: "#333333"
                                    wrapMode: Text.WordWrap
                                }

                                Text {
                                    text: "• To improve our service (we continually strive to improve our service offerings based on the information and feedback we receive from you)"
                                    font.pixelSize: 16
                                    color: "#333333"
                                    wrapMode: Text.WordWrap
                                }

                                Text {
                                    text: "• To process transactions"
                                    font.pixelSize: 16
                                    color: "#333333"
                                    wrapMode: Text.WordWrap
                                }

                                Text {
                                    text: "• To administer a contest, promotion, survey or other site feature"
                                    font.pixelSize: 16
                                    color: "#333333"
                                    wrapMode: Text.WordWrap
                                }

                                Text {
                                    text: "• To send periodic emails"
                                    font.pixelSize: 16
                                    color: "#333333"
                                    wrapMode: Text.WordWrap
                                }
            }
        }

        // Back Button
        Button {
            text: "Back"
            Layout.alignment: Qt.AlignHCenter
            Layout.preferredWidth: 200
            Layout.preferredHeight: 50

            background: Rectangle {
                color: "transparent"
                border.color: "#2196F3"
                border.width: 2
                radius: 6
            }

            contentItem: Text {
                text: parent.text
                color: "#2196F3"
                horizontalAlignment: Text.AlignHCenter
                verticalAlignment: Text.AlignVCenter
                font.pixelSize: 16
            }

            onClicked: stackView.pop()
        }
    }
}
